In [126]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [90]:
df = pd.read_csv("placement_dataset .csv")
df

,Student_ID,Branch,College_Tier,CGPA,Percentage_10th,Percentage_12th,Active_Backlogs,Gap_Years,DSA_Proficiency,Languages_Known,...,Hackathons_Won,Num_Internships,Internship_Relevance,Communication_Score,Aptitude_Score,Leadership_Roles,Companies_Applied,Companies_Shortlisted,Placed,CTC_LPA
0,SIT20240001,ECE,1,8.46,78.6,75.7,1,0,Intermediate,"C, C++, JavaScript",...,2,1,High,4.6,64.3,No,17,2,No,0.00
1,SIT20240002,ISE,3,6.27,66.4,81.6,0,0,Advanced,"C++, C",...,1,1,Medium,10.0,68.3,Yes,5,4,Yes,8.16
2,SIT20240003,ISE,3,7.42,86.3,70.8,0,0,Intermediate,"Python, Go, JavaScript, C++",...,0,0,NaN,6.1,80.9,No,16,4,Yes,4.86
3,SIT20240004,ISE,3,7.43,80.0,76.0,0,0,Advanced,"C, Rust, Java",...,0,0,NaN,4.0,47.0,Yes,7,4,Yes,7.00
4,SIT20240005,ISE,1,9.28,86.8,72.8,1,0,Intermediate,"Go, Python",...,2,1,Medium,7.4,62.5,No,6,6,Yes,9.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,SIT20240246,CSE,3,7.53,98.0,66.2,0,0,Intermediate,"JavaScript, Go",...,1,1,Medium,6.9,43.5,No,13,8,Yes,5.63
246,SIT20240247,DS,3,6.31,68.2,85.3,0,0,Intermediate,"Python, C++, Go",...,0,0,NaN,7.0,42.1,No,12,6,Yes,10.39
247,SIT20240248,CSE,2,7.61,86.9,84.7,0,2,Intermediate,"Rust, Python, Java",...,1,0,NaN,6.5,62.2,Yes,20,2,Yes,9.98
248,SIT20240249,ECE,2,8.08,84.8,77.0,0,0,Intermediate,"Python, Rust",...,2,1,Low,8.5,45.7,Yes,7,3,Yes,6.65
249,SIT20240250,CSE,2,7.14,82.7,74.6,0,0,Beginner,"Rust, JavaScript, C, C++",...,0,2,Medium,9.3,68.1,No,18,4,Yes,5.56

In [91]:
df.isnull().sum()

Student_ID                 0
Branch                     0
College_Tier               0
CGPA                       0
Percentage_10th            0
Percentage_12th            0
Active_Backlogs            0
Gap_Years                  0
DSA_Proficiency            0
Languages_Known            0
ML_AI_Skills             103
Web_Dev_Skills           107
Num_Projects               0
GitHub_Repos               0
Num_Certifications         0
Hackathons_Won             0
Num_Internships            0
Internship_Relevance      74
Communication_Score        0
Aptitude_Score             0
Leadership_Roles           0
Companies_Applied          0
Companies_Shortlisted      0
Placed                     0
CTC_LPA                    0
dtype: int64

In [92]:
df.drop(["Student_ID" , "CTC_LPA" , "Percentage_10th" , "Percentage_12th" , "Languages_Known"] , axis = 1 , inplace = True)

In [93]:
df

,Branch,College_Tier,CGPA,Active_Backlogs,Gap_Years,DSA_Proficiency,ML_AI_Skills,Web_Dev_Skills,Num_Projects,GitHub_Repos,Num_Certifications,Hackathons_Won,Num_Internships,Internship_Relevance,Communication_Score,Aptitude_Score,Leadership_Roles,Companies_Applied,Companies_Shortlisted,Placed
0,ECE,1,8.46,1,0,Intermediate,Basic,NaN,4,6,6,2,1,High,4.6,64.3,No,17,2,No
1,ISE,3,6.27,0,0,Advanced,Intermediate,Basic,2,3,2,1,1,Medium,10.0,68.3,Yes,5,4,Yes
2,ISE,3,7.42,0,0,Intermediate,Basic,NaN,2,3,1,0,0,NaN,6.1,80.9,No,16,4,Yes
3,ISE,3,7.43,0,0,Advanced,Basic,Intermediate,2,5,0,0,0,NaN,4.0,47.0,Yes,7,4,Yes
4,ISE,1,9.28,1,0,Intermediate,Basic,Basic,3,6,2,2,1,Medium,7.4,62.5,No,6,6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,CSE,3,7.53,0,0,Intermediate,Advanced,NaN,1,1,1,1,1,Medium,6.9,43.5,No,13,8,Yes
246,DS,3,6.31,0,0,Intermediate,Intermediate,NaN,1,3,1,0,0,NaN,7.0,42.1,No,12,6,Yes
247,CSE,2,7.61,0,2,Intermediate,Intermediate,NaN,3,5,3,1,0,NaN,6.5,62.2,Yes,20,2,Yes
248,ECE,2,8.08,0,0,Intermediate,Intermediate,NaN,3,4,3,2,1,Low,8.5,45.7,Yes,7,3,Yes
249,CSE,2,7.14,0,0,Beginner,Advanced,NaN,3,5,1,0,2,Medium,9.3,68.1,No,18,4,Yes

In [94]:
print(df['ML_AI_Skills'].unique())
print(df['Web_Dev_Skills'].unique())
print(df['Internship_Relevance'].unique())
print(df['Leadership_Roles'].unique())

['Basic' 'Intermediate' nan 'Advanced']
[nan 'Basic' 'Intermediate' 'Advanced']
['High' 'Medium' nan 'Low']
['No' 'Yes']

In [95]:
print(df['DSA_Proficiency'].unique())
print(df['Placed'].unique())

['Intermediate' 'Advanced' 'Beginner']
['No' 'Yes']

In [96]:
df.fillna("None" , inplace=True)

In [97]:
print(df['ML_AI_Skills'].unique())
print(df['Web_Dev_Skills'].unique())
print(df['Internship_Relevance'].unique())
print(df['Leadership_Roles'].unique())

['Basic' 'Intermediate' 'None' 'Advanced']
['None' 'Basic' 'Intermediate' 'Advanced']
['High' 'Medium' 'None' 'Low']
['No' 'Yes']

In [98]:
df

,Branch,College_Tier,CGPA,Active_Backlogs,Gap_Years,DSA_Proficiency,ML_AI_Skills,Web_Dev_Skills,Num_Projects,GitHub_Repos,Num_Certifications,Hackathons_Won,Num_Internships,Internship_Relevance,Communication_Score,Aptitude_Score,Leadership_Roles,Companies_Applied,Companies_Shortlisted,Placed
0,ECE,1,8.46,1,0,Intermediate,Basic,None,4,6,6,2,1,High,4.6,64.3,No,17,2,No
1,ISE,3,6.27,0,0,Advanced,Intermediate,Basic,2,3,2,1,1,Medium,10.0,68.3,Yes,5,4,Yes
2,ISE,3,7.42,0,0,Intermediate,Basic,None,2,3,1,0,0,None,6.1,80.9,No,16,4,Yes
3,ISE,3,7.43,0,0,Advanced,Basic,Intermediate,2,5,0,0,0,None,4.0,47.0,Yes,7,4,Yes
4,ISE,1,9.28,1,0,Intermediate,Basic,Basic,3,6,2,2,1,Medium,7.4,62.5,No,6,6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,CSE,3,7.53,0,0,Intermediate,Advanced,None,1,1,1,1,1,Medium,6.9,43.5,No,13,8,Yes
246,DS,3,6.31,0,0,Intermediate,Intermediate,None,1,3,1,0,0,None,7.0,42.1,No,12,6,Yes
247,CSE,2,7.61,0,2,Intermediate,Intermediate,None,3,5,3,1,0,None,6.5,62.2,Yes,20,2,Yes
248,ECE,2,8.08,0,0,Intermediate,Intermediate,None,3,4,3,2,1,Low,8.5,45.7,Yes,7,3,Yes
249,CSE,2,7.14,0,0,Beginner,Advanced,None,3,5,1,0,2,Medium,9.3,68.1,No,18,4,Yes

In [99]:
transformer = ColumnTransformer(transformers =[
    ('tnf1', OneHotEncoder(drop = 'first' , sparse_output = False) , ['Branch'] ),
    ('tnf2' , OrdinalEncoder(categories = [['Beginner' , 'Intermediate' , 'Advanced']]) , ['DSA_Proficiency']),
    ('tnf3' , OrdinalEncoder(categories = [['None' , 'Basic' , 'Intermediate' , 'Advanced']]) , ['ML_AI_Skills']),
    ('tnf4' , OrdinalEncoder(categories = [['None' , 'Basic' , 'Intermediate' , 'Advanced']]) , ['Web_Dev_Skills']),
    ('tnf5' , OrdinalEncoder(categories = [['None' , 'Low' , 'Medium' , 'High']]) , ['Internship_Relevance']),
    ('tnf6' , OrdinalEncoder(categories = [['No' , 'Yes']]) , ['Leadership_Roles']),
],remainder = 'passthrough')

In [100]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['Branch']),
                                ('tnf2',
                                 OrdinalEncoder(categories=[['Beginner',
                                                             'Intermediate',
                                                             'Advanced']]),
                                 ['DSA_Proficiency']),
                                ('tnf3',
                                 OrdinalEncoder(categories=[['None', 'Basic',
                                                             'Intermediate',
                                                             'Advanced']]),
                                 ['ML_AI_Skills']),
                                ('tnf4',
                                 OrdinalEncoder(categories=[['None', 'Basic',
                                                             'Intermediate',
                                                             'Advanced']]),
                                 ['Web_Dev_Skills']),
                                ('tnf5',
                                 OrdinalEncoder(categories=[['None', 'Low',
                                                             'Medium',
                                                             'High']]),
                                 ['Internship_Relevance']),
                                ('tnf6',
                                 OrdinalEncoder(categories=[['No', 'Yes']]),
                                 ['Leadership_Roles'])])

In [101]:
df

,Branch,College_Tier,CGPA,Active_Backlogs,Gap_Years,DSA_Proficiency,ML_AI_Skills,Web_Dev_Skills,Num_Projects,GitHub_Repos,Num_Certifications,Hackathons_Won,Num_Internships,Internship_Relevance,Communication_Score,Aptitude_Score,Leadership_Roles,Companies_Applied,Companies_Shortlisted,Placed
0,ECE,1,8.46,1,0,Intermediate,Basic,None,4,6,6,2,1,High,4.6,64.3,No,17,2,No
1,ISE,3,6.27,0,0,Advanced,Intermediate,Basic,2,3,2,1,1,Medium,10.0,68.3,Yes,5,4,Yes
2,ISE,3,7.42,0,0,Intermediate,Basic,None,2,3,1,0,0,None,6.1,80.9,No,16,4,Yes
3,ISE,3,7.43,0,0,Advanced,Basic,Intermediate,2,5,0,0,0,None,4.0,47.0,Yes,7,4,Yes
4,ISE,1,9.28,1,0,Intermediate,Basic,Basic,3,6,2,2,1,Medium,7.4,62.5,No,6,6,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,CSE,3,7.53,0,0,Intermediate,Advanced,None,1,1,1,1,1,Medium,6.9,43.5,No,13,8,Yes
246,DS,3,6.31,0,0,Intermediate,Intermediate,None,1,3,1,0,0,None,7.0,42.1,No,12,6,Yes
247,CSE,2,7.61,0,2,Intermediate,Intermediate,None,3,5,3,1,0,None,6.5,62.2,Yes,20,2,Yes
248,ECE,2,8.08,0,0,Intermediate,Intermediate,None,3,4,3,2,1,Low,8.5,45.7,Yes,7,3,Yes
249,CSE,2,7.14,0,0,Beginner,Advanced,None,3,5,1,0,2,Medium,9.3,68.1,No,18,4,Yes

In [114]:
x = df.iloc[ :  , : 19]
x

,Branch,College_Tier,CGPA,Active_Backlogs,Gap_Years,DSA_Proficiency,ML_AI_Skills,Web_Dev_Skills,Num_Projects,GitHub_Repos,Num_Certifications,Hackathons_Won,Num_Internships,Internship_Relevance,Communication_Score,Aptitude_Score,Leadership_Roles,Companies_Applied,Companies_Shortlisted
0,ECE,1,8.46,1,0,Intermediate,Basic,None,4,6,6,2,1,High,4.6,64.3,No,17,2
1,ISE,3,6.27,0,0,Advanced,Intermediate,Basic,2,3,2,1,1,Medium,10.0,68.3,Yes,5,4
2,ISE,3,7.42,0,0,Intermediate,Basic,None,2,3,1,0,0,None,6.1,80.9,No,16,4
3,ISE,3,7.43,0,0,Advanced,Basic,Intermediate,2,5,0,0,0,None,4.0,47.0,Yes,7,4
4,ISE,1,9.28,1,0,Intermediate,Basic,Basic,3,6,2,2,1,Medium,7.4,62.5,No,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,CSE,3,7.53,0,0,Intermediate,Advanced,None,1,1,1,1,1,Medium,6.9,43.5,No,13,8
246,DS,3,6.31,0,0,Intermediate,Intermediate,None,1,3,1,0,0,None,7.0,42.1,No,12,6
247,CSE,2,7.61,0,2,Intermediate,Intermediate,None,3,5,3,1,0,None,6.5,62.2,Yes,20,2
248,ECE,2,8.08,0,0,Intermediate,Intermediate,None,3,4,3,2,1,Low,8.5,45.7,Yes,7,3
249,CSE,2,7.14,0,0,Beginner,Advanced,None,3,5,1,0,2,Medium,9.3,68.1,No,18,4

In [115]:
le = LabelEncoder()
y = le.fit_transform(df['Placed'])
y

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1])

In [116]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [117]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0])

In [118]:
x_train_transformed = transformer.fit_transform(x_train)
x_test_transformed = transformer.transform(x_test)

In [119]:
x_train_transformed

array([[ 0. ,  0. ,  0. , ..., 45.7,  7. ,  3. ],
       [ 0. ,  0. ,  0. , ..., 60.5, 18. ,  7. ],
       [ 0. ,  0. ,  0. , ..., 58.3, 20. ,  6. ],
       ...,
       [ 0. ,  0. ,  0. , ..., 90.6, 19. ,  2. ],
       [ 0. ,  1. ,  0. , ..., 62.2, 20. ,  2. ],
       [ 0. ,  0. ,  0. , ..., 68.1,  7. ,  2. ]], shape=(200, 25))

In [120]:
x_train_transformed.shape

(200, 25)

In [121]:
print(type(x_train_transformed))

<class 'numpy.ndarray'>

In [122]:
x_train_df = pd.DataFrame(
    x_train_transformed ,
    columns = transformer.get_feature_names_out()
)
x_train_df

,tnf1__Branch_CIVIL,tnf1__Branch_CSE,tnf1__Branch_DS,tnf1__Branch_ECE,tnf1__Branch_EEE,tnf1__Branch_ISE,tnf1__Branch_ME,tnf2__DSA_Proficiency,tnf3__ML_AI_Skills,tnf4__Web_Dev_Skills,...,remainder__Gap_Years,remainder__Num_Projects,remainder__GitHub_Repos,remainder__Num_Certifications,remainder__Hackathons_Won,remainder__Num_Internships,remainder__Communication_Score,remainder__Aptitude_Score,remainder__Companies_Applied,remainder__Companies_Shortlisted
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,...,0.0,3.0,4.0,3.0,2.0,1.0,8.5,45.7,7.0,3.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,...,0.0,1.0,4.0,1.0,1.0,1.0,8.5,60.5,18.0,7.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,3.0,5.0,6.0,0.0,1.0,5.1,58.3,20.0,6.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,...,0.0,4.0,6.0,4.0,2.0,1.0,4.7,59.6,16.0,3.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,2.0,2.0,...,0.0,2.0,3.0,1.0,1.0,0.0,8.5,60.7,9.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,0.0,2.0,2.0,3.0,3.0,0.0,7.7,66.8,14.0,7.0
196,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,...,0.0,4.0,7.0,3.0,1.0,0.0,7.5,89.4,15.0,1.0
197,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,2.0,0.0,1.0,0.0,6.4,90.6,19.0,2.0
198,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,...,2.0,3.0,5.0,3.0,1.0,0.0,6.5,62.2,20.0,2.0
199,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,5.0,6.0,4.0,2.0,2.0,5.1,68.1,7.0,2.0

In [123]:
model = DecisionTreeClassifier()
model.fit(x_train_transformed , y_train)

DecisionTreeClassifier()

In [125]:
y_pred = model.predict(x_test_transformed)

In [127]:
print('Accuracy Score :-' , accuracy_score(y_pred , y_test))

Accuracy Score :- 0.82